protocols = imap pop3

auth_mechanisms = plain login
disable_plaintext_auth = yes
mail_location = maildir:~/Maildir
first_valid_uid = 1000

ssl = required
ssl_min_protocol = TLSv1.2
ssl_cert = </etc/pki/tls/certs/mail.garea.local-fullchain.pem
ssl_key = </etc/pki/tls/private/mail.garea.local.key.pem
ssl_cipher_list = PROFILE=SYSTEM

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}
